**Projek 1**


Kelompok 1

Disusun oleh:  
Achmad Fadhlih Saldy Saputra (1306621060)  
Achmad Nurnaafi (1306620057)  
Haryanto (1306620059)  
Yohanes Radito Putra (1306620048)


---
Metode Dekomposisi LU
---

In [ ]:
import numpy as np
from scipy.linalg import lu_factor, lu_solve

A = np.array([[ 3600,  0,    0,     0,     -4000  ],
              [ -3600, 3600, 0,     0,     0      ],
              [ 0,    -3600, 3600,  0,     0      ],
              [ 0,     0,    -3600, 3600,  0      ],
              [ 0,     0,    0,     -3600, -400   ]])
B = np.array([-40, 0, 0, 0, 0])

n = A.shape[0]

# Inisialisasi matriks L dan U dengan nol
L = np.zeros((n, n))
U = np.zeros((n, n))

# Iterasi untuk menghitung matriks L dan U
for k in range(n):
    L[k, k] = 1.0
    for i in range(k+1):
        U[i, k] = A[i, k] - np.dot(L[i, :i], U[:i, k])
    for i in range(k+1, n):
        L[i, k] = (A[i, k] - np.dot(L[i, :k], U[:k, k])) / U[k, k]

# Menyelesaikan sistem persamaan linear Ax = B
LU, piv = lu_factor(A)
c = lu_solve((LU, piv), B, overwrite_b=True)

print("Matriks A:")
print(A)
print()

print("Matriks L:")
print(L)
print()

print("Matriks U:")
print(U)
print()

print("Matriks B:")
print(B)
print()

print("Hasil:")
print(c)


Matriks A:
[[ 3600     0     0     0 -4000]
 [-3600  3600     0     0     0]
 [    0 -3600  3600     0     0]
 [    0     0 -3600  3600     0]
 [    0     0     0 -3600  -400]]

Matriks L:
[[ 1.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [ 0. -1.  1.  0.  0.]
 [ 0.  0. -1.  1.  0.]
 [ 0.  0.  0. -1.  1.]]

Matriks U:
[[ 3600.     0.     0.     0. -4000.]
 [    0.  3600.     0.     0. -4000.]
 [    0.     0.  3600.     0. -4000.]
 [    0.     0.     0.  3600. -4000.]
 [    0.     0.     0.     0. -4400.]]

Matriks B:
[-40   0   0   0   0]

Hasil:
[-0.0010101  -0.0010101  -0.0010101  -0.0010101   0.00909091]


---
Metode Gauss Naive
---

In [ ]:
kelompok = """
Metode Gauss Naive
Kelompok 1
"""
print(kelompok)

import numpy as np
import sys

# Matriks koefisien
A = np.array([[ 3600,  0,    0,     0,     -4000  ],
              [ -3600, 3600, 0,     0,     0      ],
              [ 0,    -3600, 3600,  0,     0      ],
              [ 0,     0,    -3600, 3600,  0      ],
              [ 0,     0,    0,     -3600, -400   ]])

# Vektor hasil
b = np.array([-40, 0, 0, 0, 0])

# Jumlah variabel
n = len(b)

# Matriks gabungan A dan b
AB = np.concatenate((A, np.reshape(b, (n, 1))), axis=1)

# Menampilkan matriks A, b, dan gabungan AB
print("Matriks A:\n", A, "\nVektor b:\n", b, "\n")
print("Matriks gabungan:\n", AB)

# Inisialisasi vektor solusi
c = np.zeros(n)

# Eliminasi Gauss
for i in range(n):
    # Cek apakah terdapat pembagian dengan nol
    if AB[i][i] == 0.0:
        sys.exit('Terdeteksi pembagian dengan nol')

    for j in range(i+1, n):
        # Rasio pengurangan baris
        ratio = AB[j][i]/AB[i][i]

        for k in range(n+1):
            # Pengurangan baris
            AB[j][k] = AB[j][k] - ratio * AB[i][k]

# Substitusi mundur
c[n-1] = AB[n-1][n]/AB[n-1][n-1]

for i in range(n-2,-1,-1):
    c[i] = AB[i][n]

    for j in range(i+1,n):
        c[i] = c[i] - AB[i][j]*c[j]

    c[i] = c[i]/AB[i][i]

# Menampilkan solusi
print("hasil: ")
print(c)



Metode Gauss Naive
Kelompok 1

Matriks A:
 [[ 3600     0     0     0 -4000]
 [-3600  3600     0     0     0]
 [    0 -3600  3600     0     0]
 [    0     0 -3600  3600     0]
 [    0     0     0 -3600  -400]] 
Vektor b:
 [-40   0   0   0   0] 

Matriks gabungan:
 [[ 3600     0     0     0 -4000   -40]
 [-3600  3600     0     0     0     0]
 [    0 -3600  3600     0     0     0]
 [    0     0 -3600  3600     0     0]
 [    0     0     0 -3600  -400     0]]
hasil: 
[-0.0010101  -0.0010101  -0.0010101  -0.0010101   0.00909091]


---
Metode Gauss-Jordan
---

In [ ]:
kelompok = """
Metode Gauss-Jordan
Kelompok 1
"""
print(kelompok)

import numpy as np

# definisikan matriks A dan b
A = np.array([[ 3600,  0,    0,     0,     -4000  ],
              [ -3600, 3600, 0,     0,     0      ],
              [ 0,    -3600, 3600,  0,     0      ],
              [ 0,     0,    -3600, 3600,  0      ],
              [ 0,     0,    0,     -3600, -400   ]], float)
b = np.array([-40, 0, 0, 0, 0], float)

# gabungkan matriks A dan vektor b
AB = np.hstack((A, b.reshape(-1, 1)))

# tampilkan matriks awal
print("Matriks A:")
print(A)
print()
print("Matriks B:")
print(b)
print()
print("Matriks gabungan A dan B:")
print()
print(AB)

# proses eliminasi Gauss-Jordan
n = len(b)
for i in range(n):
    # membuat leading coefficient menjadi 1
    faktor = AB[i,i]
    AB[i] /= faktor
    
    # eliminasi ke bawah
    for j in range(i+1, n):
        faktor = AB[j,i] / AB[i,i]
        AB[j] -= faktor * AB[i]
    
    # eliminasi ke atas
    for j in range(i):
        faktor = AB[j,i] / AB[i,i]
        AB[j] -= faktor * AB[i]

# solusi
c = AB[:, -1]
print()
print("hasil:")
print(c)



Metode Gauss-Jordan
Kelompok 1

Matriks A:
[[ 3600.     0.     0.     0. -4000.]
 [-3600.  3600.     0.     0.     0.]
 [    0. -3600.  3600.     0.     0.]
 [    0.     0. -3600.  3600.     0.]
 [    0.     0.     0. -3600.  -400.]]

Matriks B:
[-40.   0.   0.   0.   0.]

Matriks gabungan A dan B:

[[ 3600.     0.     0.     0. -4000.   -40.]
 [-3600.  3600.     0.     0.     0.     0.]
 [    0. -3600.  3600.     0.     0.     0.]
 [    0.     0. -3600.  3600.     0.     0.]
 [    0.     0.     0. -3600.  -400.     0.]]

hasil:
[-0.0010101  -0.0010101  -0.0010101  -0.0010101   0.00909091]


---
Metode invers balikan
---

In [ ]:
kelompok = """
Metode Matrix Balikan
Kelompok 1
"""
print(kelompok)

import numpy as np

# definisikan matriks A dan b
A = np.array([[ 3600,  0,    0,     0,     -4000  ],
              [ -3600, 3600, 0,     0,     0      ],
              [ 0,    -3600, 3600,  0,     0      ],
              [ 0,     0,    -3600, 3600,  0      ],
              [ 0,     0,    0,     -3600, -400   ]], float)
b = np.array([-40, 0, 0, 0, 0], float)

# tampilkan matriks awal
print("Matriks awal:")
print(A)
print()

# hitung invers matriks A
A_inv = np.linalg.inv(A)

# tampilkan invers matriks A
print("Invers matriks A:")
for row in A_inv:
    print("[", "  ".join([f"{elem:8.5f}" for elem in row]), "]")
print()

# hitung solusi x
x = A_inv.dot(b)
print("Solusinya:")
print(x)



Metode Matrix Balikan
Kelompok 1

Matriks awal:
[[ 3600.     0.     0.     0. -4000.]
 [-3600.  3600.     0.     0.     0.]
 [    0. -3600.  3600.     0.     0.]
 [    0.     0. -3600.  3600.     0.]
 [    0.     0.     0. -3600.  -400.]]

Invers matriks A:
[  0.00003  -0.00025  -0.00025  -0.00025  -0.00025 ]
[  0.00003   0.00003  -0.00025  -0.00025  -0.00025 ]
[  0.00003   0.00003   0.00003  -0.00025  -0.00025 ]
[  0.00003   0.00003   0.00003   0.00003  -0.00025 ]
[ -0.00023  -0.00023  -0.00023  -0.00023  -0.00023 ]

Solusinya:
[-0.0010101  -0.0010101  -0.0010101  -0.0010101   0.00909091]
